export const FETCH_ALL = "FETCH_UPDATE";
export const CREATE_SUGGESTION = "CREATE_SUGGESTION";
export const FETCH_SORTED = "FETCH_SORTED";
export const FETCH_FILTERED = "FETCH_FILTERED";
export const CHANGE_TYPE = "CHANGE_TYPE";
