export const FETCH_ALL = "FETCH_UPDATE";
export const FETCH_SUGGESTION = "FETCH_SUGGESTION";
export const CREATE_SUGGESTION = "CREATE_SUGGESTION";
export const DELETE_SUGGESTION = "DELETE_SUGGESTION";
export const UPVOTE = "UPVOTE";
export const FETCH_SORTED = "FETCH_SORTED";
export const FETCH_FILTERED = "FETCH_FILTERED";
export const CHANGE_FILTERS = "CHANGE_FILTERS";
export const CHANGE_TYPE = "CHANGE_TYPE";

export const START_LOADING = "START_LOADING";
export const END_LOADING = "END_LOADING";

export const AUTH = "AUTH";
export const LOGOUT = "LOGOUT";
